#pragma once
#include <Arduino.h>

#define FLASH_INIT_UCHAR 0U
#define PLAN_SELECTED_UCHAR 1U
#define ALARM_DURATION_UINT 4U
#define MENU_SCREEN_BLANKING_BOOL 8U
#define ALARMS_HALTED_BOOL 9U
#define PLAN_0_OFFSET_UINT 256U
#define PLAN_1_OFFSET_UINT 512U
#define PLAN_2_OFFSET_UINT 768U
#define PLAN_3_OFFSET_UINT 1024U
#define PLAN_4_OFFSET_UINT 1280U
#define PLAN_0_WEEKDAYS_UCHAR 20U
#define PLAN_1_WEEKDAYS_UCHAR 21U
#define PLAN_2_WEEKDAYS_UCHAR 22U
#define PLAN_3_WEEKDAYS_UCHAR 23U
#define PLAN_4_WEEKDAYS_UCHAR 24U
#define PLAN_0_NAME_STRING 1536U
#define PLAN_1_NAME_STRING 1569U
#define PLAN_2_NAME_STRING 1602U
#define PLAN_3_NAME_STRING 1635U
#define PLAN_4_NAME_STRING 1668U
#define WEBSERVER_PASSWORD 1701U